# Generated by Django 6.0.2 on 2026-04-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='actualzado',
            new_name='actualizado',
        ),
    ]
